#!/usr/bin/python3
for i in range(97, 123):
    alpha =chr(i)
    if i == 101 or i == 113:
        continue
    print("{}".format(alpha), end="")



#    if i == 101 or i == 113:
#        continue
#    print("{}".format(chr(i)), end="")